title: Box of Rad
description: Thoughts on Programming and Faith by Daniel Upton

url: http://www.boxofrad.com/
baseurl: ""
paginate_path: "blog/page/:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About Me
   url: /about

social:
   github: boxofrad
   twitter: boxofrad
   facebook: daniel.upton

google_analytics: "UA-65292437-1"
